/* Generated By:JavaCC: Do not edit this line. TallerLPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TallerLPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DESAYUNO = 5;
  /** RegularExpression Id. */
  int ALMUERZO = 6;
  /** RegularExpression Id. */
  int CENA = 7;
  /** RegularExpression Id. */
  int MERIENDA = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DESAYUNO>",
    "<ALMUERZO>",
    "<CENA>",
    "<MERIENDA>",
  };

}
